# Generated by Django 5.1.4 on 2024-12-07 22:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'ordering': ('id',), 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='myuser',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, validators=[django.core.validators.MaxValueValidator], verbose_name='Возраст'),
        ),
    ]
